### ISSUE TITLE
Каким образом и как часто формируется rublock-list?

### ISSUE THREAD

**Issue by dansoftware** [blackcofee/rublock-list#1]
Подскажите, как часто обновляется и как формируются списки rublock-list? С какой целью clear.sh убирает часть URL?
Например, есть хост bt4.t-ru.org [195.82.146.123]. Это трекер https://rutracker.org/ Он заблокирован только по IP: https://reestr.rublacklist.net/record/467091/ Но ни в одном из списков rublock-list его нет.

**Comment by blackcofee** [comment]
1) Парсится с rublacklist.net каждые 3 часа, как часто они они обновляют не известно. 
2) clear.sh удаляет  не заблокированные сайты, но числящиеся в списках + сокращаем список за счет удаления различных казино и т.д. 
3) Парсятся только заблокированные домены, но часть ip попадает туда. 
4) Трекеры торрентов не рекомендую разблокировать при использовании vpn, просто прилетит аббуз и его заблокируют. 

В скрипте можно переключиться на другой источник antizapret, но он постоянно лежал в последнее время.

**Comment by dansoftware** [comment]
Спасибо за разъяснения. Но п. 4 я не понял. Я вручную добавил трекер bt4.t-ru.org [195.82.146.123] в список, сейчас трафик к нему идет через VPN. Чем это чревато?

**Comment by blackcofee** [comment]
При направлении трафика к трекеру через vpn, в статистике качающих/раздающих будет светится ip твоего vpn. Во многих странах эти трекеры мониторят,  определяют страну, физ. лицо ты или компания.  Если физ. лицо отпраляют штраф, если зарегистрировано на компанию, то оправляют абуз (жалобу), владелец сервиса ищет пользователя на которого поступила жалоба и блокирует доступ без каких либо предупреждений.

**Comment by dansoftware** [comment]
Ясно, спасибо. Скажем так, в моем случае предусмотрено подобного рода развитие событий. Думаю, тему можно закрывать.
